name: Concrete Saplings
favicon: null
layout_spectrum: 0.25529
typography_spectrum: 0.50471
title: TAIKOPROJECT + Quetzal in Collaboration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#455046'
    - '#b0b2a8'
    - '#8e8673'
  brandStrength: 0.9924955326132476
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
